export const REQUEST_TODOS = "REQUEST_TODOS";
export const RECEIVE_TODOS = "RECEIVE_TODOS";

export const POST_TODO = "POST_TODO";
export const RECEIVE_TODO = "RECEIVE_TODO";

export const PUT_TODO = "PUT_TODO";
export const RECEIVE_EDITED_TODO = "RECEIVE_EDITED_TODO";

export const REQUEST_ENTRIES = "REQUEST_ENTRIES";
export const RECEIVE_ENTRIES = "RECEIVE_ENTRIES";

export const POST_ENTRY = "POST_ENTRY";
export const RECEIVE_ENTRY = "RECEIVE_ENTRY";

export const PUT_ENTRY = "PUT_ENTRY";
export const RECEIVE_EDITED_ENTRY = "RECEIVE_EDITED_ENTRY";

export const POST_USER = "POST_USER";
export const RECEIVE_USER = "RECEIVE_USER";

export const POST_LOGIN = "POST_LOGIN";
export const RECEIVE_LOGIN = "RECEIVE_LOGIN";

export const GET_LOGOUT = "GET_LOGOUT";
export const RECEIVE_LOGOUT = "RECEIVE_LOGOUT";

export default {
  REQUEST_TODOS,
  RECEIVE_TODOS,

  POST_TODO,
  RECEIVE_TODO,

  PUT_TODO,
  RECEIVE_EDITED_TODO,

  REQUEST_ENTRIES,
  RECEIVE_ENTRIES,

  POST_ENTRY,
  RECEIVE_ENTRY,

  PUT_ENTRY,
  RECEIVE_EDITED_ENTRY,

  POST_USER,
  RECEIVE_USER,

  POST_LOGIN,
  RECEIVE_LOGIN,

  GET_LOGOUT,
  RECEIVE_LOGOUT,
};
